[package]
name = "winscreenshot"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
win-screenshot = "2.0"
ctrlc = "3.2"
chrono = "0.4"
